spring.application.name=library

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

library.security.jwt-secret=${JWT_SECRET:change-me-change-me-change-me-change-me}
library.security.access-token-ttl=${ACCESS_TOKEN_TTL:PT30M}
library.security.refresh-token-ttl=${REFRESH_TOKEN_TTL:P30D}

library.openapi.base-url=${OPEN_LIBRARY_BASE_URL:https://openlibrary.org}
library.cache.home-ttl=${CACHE_HOME_TTL:PT6H}
library.cache.search-ttl=${CACHE_SEARCH_TTL:PT1H}
library.cache.subject-ttl=${CACHE_SUBJECT_TTL:PT6H}
library.cache.book-ttl=${CACHE_BOOK_TTL:PT24H}
library.cache.author-ttl=${CACHE_AUTHOR_TTL:PT168H}
library.cache.stale-window=${CACHE_STALE_WINDOW:PT72H}
